language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
sudo: false
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: IVupBRoAqymbBjA+yNjflcUHYLsHjKBO35QolW48mqsSThMrqWr4bYQUaKkWL1ptLzz5OOc2fGuk/cPG+coMMHJc5tXuaw5gtOgEokcNb+khCyxyd/xdDWNHbfDPHlEqdtb0ypVjm8WfNGvuzJBrlUVfgm9ZEtmVTIyWaQn6duk=
  file:
    - 'nlcst-emoji-modifier.js'
    - 'nlcst-emoji-modifier.min.js'
  on:
    tags: true
